### ISSUE TITLE
Replicate Laravel's artisan make:auth

### ISSUE THREAD

**Issue by bbloom** [LaSalleSoftware/lsv2-library-pkg#2]
Replicate Laravel's out-of-the-box login, logout, and registration, which is done with `php artisan make:auth`.  

Want to get this built into this package as my starting point for building out further related custom features.

This initial replication includes setting up language files in this package, cleaning up the views (especially want to remove all javascript), making the views more Dusk friendly, and dealing with whatever comes up whilst going through this exercise.

**Comment by bbloom** [comment]
I should add that I will do integration tests in the front-end app.

**Comment by LaSalleSoftware** [comment]
Done. 

The Dusk tests are mostly undone. I have significant changes coming anyways. 

Final commit in https://github.com/LaSalleSoftware/lsv2-library-pkg/issues/1#issue-378836648 should have been applied to this issue.
