### ISSUE TITLE
Set up an "activities" database lookup table

### ISSUE THREAD

**Issue by LaSalleSoftware** [LaSalleSoftware/lsv2-library-pkg#5]
While working on the UUIDs ( #4 ), I am creating a database table where all the created UUID's are stored. In this table I want to associate a UUID with the activity that created that UUID. So I need another database table for these activities.

A wider feature involving custom software activities (I am avoiding the word "events") is planned. But for the time being, I need the database lookup table and a seeder for the UUID. 

With this wider feature in mind, I am creating this issue for future reference.

**Comment by bbloom** [comment]
See https://github.com/LaSalleSoftware/lsv2-basicfrontend-app/issues/3
